### ISSUE TITLE
cpu - profile and record results

### ISSUE THREAD

**Issue by lastephey** [desihub/gpu_specter#15]
When the cpu version of gpu_specter is fully ready, profile the code to understand where our major cpu bottlenecks are. 

Consider tools like PySpy, cprofile, line_profiler. 

Save/post these results somewhere they won't be lost. They will be useful for NESAP before/after speedup calculation.

**Comment by rcthomas** [comment]
Automation?

**Comment by lastephey** [comment]
Record this number so you can make your nice NESAP bar plot 

Laurie will provide info for march 2019 benchmark

Daniel will find starting number for CPU spex 

In order to have apples to apples comparison we'll need to run spex in the desi benchmark full exposure suite 

Caveat-- old and new versions may be using different versions of PSF

**Comment by lastephey** [comment]
Closing in the spirit of [Closember](https://closember.org/).
