### ISSUE TITLE
Algorithmic differences between gpu_specter and specter

### ISSUE THREAD

**Issue by marcelo-alvarez** [desihub/gpu_specter#78]
Before running DR1 / Iron on Perlmutter, we need to characterize and understand differences between extracted spectra obtained using gpu_specter and those obtained using specter.

**Comment by marcelo-alvarez** [comment]
@sbailey @dmargala does this make sense?

![frame-z5-001286802681_comparison](https://user-images.githubusercontent.com/32470484/193960937-cf321ff0-7fde-4810-ac73-cdf9141b6706.png)

**Comment by marcelo-alvarez** [comment]
Adding some context / information that may not be obvious from the above plot (which is showing the residual for the flux, i.e. f1/f2-1, where f1 and f2 are the fluxes being compared).

Generally there is a negligible (<1e-7) relative difference in the flux between gpu_specter on GPU and CPU at a fixed value of nsubbundles. There is however a more significant, but still small, difference, at the level of ~1-2e-3, between gpu_specter and specter even at fixed nsubbundles. The difference is typically of the same magnitude even when changing nsubbundles, but there are some wavelengths where the difference can become larger, such as the most prominent feature at a wavelength of ~8880, where the relative difference spikes to ~1e-2 between nsubbundle values of 5 and 6, even for specter.

**Comment by sbailey** [comment]
@marcelo-alvarez thanks.  I think this is consistent with the previous studies by Daniel, but it is good to revisit with fresh eyes and the latest code and then extending to compare redshifts.

Let's plot this normalized by the reported error to focus on differences that are statistically significant, i.e. `(f1-f2) * sqrt(ivar1)`.

It's good that gpu_specter is self consistent between GPU and CPU.

It looks like specter and gpu_specter are at least as consistent with each other as specter nsubbundles 5 vs. 6 although it's hard to tell if the red spikes are hiding blue spikes, or whether the blue spikes are more rare but bigger when they occur.  Please plot the specter nsubbundles 5 vs. 6 cases separately so that we can check that.

Please also make 2D plots of fiber vs. wavelength color coded by `(f1-f2)*sqrt(ivar)`.  That can highlight more rare cases that impact individual fibers or bundles in a way that we wouldn't see by looking at one fiber at a time.

**Comment by rainwoodman** [comment]
Round off errors can bias the mean towards zero. Different chips may run
add accumulation in different order, producing different results. but both
are biased thus difference may be not a good measure of the discrepancy
from truth. Are there algorithms to mitigate round off errors in the code?
Perhaps running with a high res float (eg 32 to 64) as the truth?

**Comment by marcelo-alvarez** [comment]
Hi @rainwoodman, I'm not sure about algorithms to mitigate round off errors. The differences we are focused on here are due to changes in the algorithm itself (either the implementation being different between codes, or the parameters controlling bundling for the same code). There are some differences at the 1e-7 level between GPU and CPU for gpu_specter that are acceptable, and for many wavelengths the difference is zero. So this indicates the accumulation of round off error is well under control for gpu_specter, even if there are no explicit algorithms in it. Perhaps because most of the computations themselves are done by numpy/cupy, and they do mitigate those kinds of errors.

**Comment by marcelo-alvarez** [comment]
> @marcelo-alvarez thanks. I think this is consistent with the previous studies by Daniel, but it is good to revisit with fresh eyes and the latest code and then extending to compare redshifts.
> 
> Let's plot this normalized by the reported error to focus on differences that are statistically significant, i.e. `(f1-f2) * sqrt(ivar1)`.
> 
> It's good that gpu_specter is self consistent between GPU and CPU.
> 
> It looks like specter and gpu_specter are at least as consistent with each other as specter nsubbundles 5 vs. 6 although it's hard to tell if the red spikes are hiding blue spikes, or whether the blue spikes are more rare but bigger when they occur. Please plot the specter nsubbundles 5 vs. 6 cases separately so that we can check that.
> 
> Please also make 2D plots of fiber vs. wavelength color coded by `(f1-f2)*sqrt(ivar)`. That can highlight more rare cases that impact individual fibers or bundles in a way that we wouldn't see by looking at one fiber at a time.

@sbailey the following includes residual normalized by rms. I am in the process of making the other plots, as instructed, and will update when they are ready.

![frame-z5-001286802681_comparison](https://user-images.githubusercontent.com/32470484/194403907-31ce5f5f-f5da-4d1c-a45d-08681ddb15dc.png)

**Comment by marcelo-alvarez** [comment]
@sbailey here is the specter nsubbundles 5 vs. 6 case you requested that I plot:
![frame-z5-001286802681_sc5-sc6](https://user-images.githubusercontent.com/32470484/194440218-d96cc8b0-0039-441b-998e-97ae6a601420.png)

I also include the other pairwise comparisons in case you might want to see those next:
![frame-z5-001286802681_gc5-gg5](https://user-images.githubusercontent.com/32470484/194440238-44712f53-91bf-4738-924a-8033c373baf6.png)
![frame-z5-001286802681_gc5-sc5](https://user-images.githubusercontent.com/32470484/194440240-8f992a7d-ed12-4335-99c0-88a8b8765b6f.png)
![frame-z5-001286802681_gc5-sc6](https://user-images.githubusercontent.com/32470484/194440242-3a7eeb6f-726a-4d74-9478-a340cf2a36bd.png)
![frame-z5-001286802681_gg5-sc5](https://user-images.githubusercontent.com/32470484/194440243-6c225637-d95e-461e-9e55-d316f8b76070.png)
![frame-z5-001286802681_gg5-sc6](https://user-images.githubusercontent.com/32470484/194440245-6b2928b4-bddc-42fc-82bb-da3d1ebb60b8.png)

I am working on the 2d plot you requested above and will update when that is ready. Mentioning @julienguy to get him in the loop on the differences at the spectrum level for the latest spectral extraction code, before extending to compare redshifts.

**Comment by marcelo-alvarez** [comment]
> Please also make 2D plots of fiber vs. wavelength color coded by `(f1-f2)*sqrt(ivar)`. That can highlight more rare cases that impact individual fibers or bundles in a way that we wouldn't see by looking at one fiber at a time.

@sbailey here are the 2D plots. I tried to follow your instructions as well as possible and, where there was some ambiguity in how to proceed, make them in such a way as to minimize the overall delay from back-and-forth iterations that would require significant modification to my plotting scripts, so I am showing all possible comparisons for the tests I have done so far. I also included the residuals f2/f1-1 and used the log of absolute value in each case. 

Hopefully this conveys the information you need to decide next steps on this while avoiding getting lost in all the file names and plots with different scales. As discussed off-github, I will also put this in a mini-report / slides / plots-with-context, to help with clarifying and focusing the discussion here and elsewhere. 

In the meantime, please let me know any revisions / any other plots you would like me to make and post here. Thanks.

![frame2d-z5-00128680-499_cori-spec-cpu-5-cori-spec-cpu-6](https://user-images.githubusercontent.com/32470484/194680232-59026639-ba3f-4943-b0ea-4d60441389ec.png)
![frame2d-z5-00128680-499_prlm-gspc-cpu-5-cori-spec-cpu-5](https://user-images.githubusercontent.com/32470484/194680233-02c73d0e-4306-47d6-bff0-7d2ca2e68083.png)
![frame2d-z5-00128680-499_prlm-gspc-cpu-5-cori-spec-cpu-6](https://user-images.githubusercontent.com/32470484/194680236-0dee4179-d645-4da2-8a4f-af9f86da689e.png)
![frame2d-z5-00128680-499_prlm-gspc-cpu-5-prlm-spec-cpu-5](https://user-images.githubusercontent.com/32470484/194680237-21d6f7ba-f326-4868-b7b8-cbeb7630528c.png)
![frame2d-z5-00128680-499_prlm-gspc-cpu-5-prlm-spec-cpu-6](https://user-images.githubusercontent.com/32470484/194680240-2fd14e08-58f0-4e0f-b967-226e1a83d939.png)
![frame2d-z5-00128680-499_prlm-gspc-gpu-5-cori-spec-cpu-5](https://user-images.githubusercontent.com/32470484/194680241-ea1d0cc4-b2bb-4c9d-9bc0-d01974729f3e.png)
![frame2d-z5-00128680-499_prlm-gspc-gpu-5-cori-spec-cpu-6](https://user-images.githubusercontent.com/32470484/194680244-8d579ee9-cfc3-46c3-ac09-eb1e79fa4d13.png)
![frame2d-z5-00128680-499_prlm-gspc-gpu-5-prlm-gspc-cpu-5](https://user-images.githubusercontent.com/32470484/194680246-c5fa783b-d507-4c53-82a2-0c37962a40cc.png)
![frame2d-z5-00128680-499_prlm-gspc-gpu-5-prlm-spec-cpu-5](https://user-images.githubusercontent.com/32470484/194680248-c7c1604a-3310-4849-806c-ab1575245ccf.png)
![frame2d-z5-00128680-499_prlm-gspc-gpu-5-prlm-spec-cpu-6](https://user-images.githubusercontent.com/32470484/194680251-eee32184-7f58-46ae-bc56-9b5c96159970.png)
![frame2d-z5-00128680-499_prlm-spec-cpu-5-cori-spec-cpu-5](https://user-images.githubusercontent.com/32470484/194680252-88995418-eb30-44e5-879d-6d90523141f3.png)
![frame2d-z5-00128680-499_prlm-spec-cpu-5-cori-spec-cpu-6](https://user-images.githubusercontent.com/32470484/194680253-92f1633c-4443-445f-8a4d-571cd03edaa3.png)
![frame2d-z5-00128680-499_prlm-spec-cpu-5-prlm-spec-cpu-6](https://user-images.githubusercontent.com/32470484/194680256-d529ccc3-89d4-4244-8c76-d37f4fd51503.png)
![frame2d-z5-00128680-499_prlm-spec-cpu-6-cori-spec-cpu-5](https://user-images.githubusercontent.com/32470484/194680259-98230909-f853-48e9-81cf-dd1076d4dad4.png)
![frame2d-z5-00128680-499_prlm-spec-cpu-6-cori-spec-cpu-6](https://user-images.githubusercontent.com/32470484/194680261-e00c6be1-6b50-4bc9-8bf0-625117cf8eb2.png)

**Comment by marcelo-alvarez** [comment]
The impact of these differences downstream to redshifts has been shown to be acceptable, as documented [here](https://desi.lbl.gov/DocDB/cgi-bin/private/ShowDocument?docid=7099). Consequently gpu_specter has been the default extraction software in the spectroscopic pipeline since [desispec #1883](https://github.com/desihub/desispec/pull/1883) and will be used going forward on Perlmutter. Closing.
